vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO topology-tool-kit/ttk
    REF 7bea8bdae18883edb7b25bb3a919b6aeac9a21a5
    SHA512 52348677a3d76685cf7d65d8f6e0a52a526c043a3e0ce92c6e232adf38192ee9bac43509997b50a15d5551440d33bc12289474e46f3566fca2c25981e788d65e
    HEAD_REF master
)

if(VCPKG_TARGET_IS_LINUX)
    set(TTK_USE_OPENMP ON)
else()
    set(TTK_USE_OPENMP OFF)
endif()

if (VCPKG_LIBRARY_LINKAGE STREQUAL "static")
    set(TTK_USE_GRAPHVIZ OFF)
    set(TTK_DISABLE_FIND_GRAPHVIZ ON)
    set(TTK_REQUIRE_FIND_GRAPHVIZ OFF)
else()
    set(TTK_USE_GRAPHVIZ ON)
    set(TTK_DISABLE_FIND_GRAPHVIZ OFF)
    set(TTK_REQUIRE_FIND_GRAPHVIZ ON)
endif()

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DCMAKE_DISABLE_FIND_PACKAGE_ParaView=ON # Don't try finding paraview.
        -DCMAKE_DISABLE_FIND_PACKAGE_Torch=ON # Optional
        -DCMAKE_DISABLE_FIND_PACKAGE_CGAL=ON
        -DCMAKE_DISABLE_FIND_PACKAGE_EMBREE=ON
        -DCMAKE_DISABLE_FIND_PACKAGE_SQLite3=ON
        -DCMAKE_DISABLE_FIND_PACKAGE_ZFP=ON
        -DCMAKE_DISABLE_FIND_PACKAGE_WEBSOCKETPP=ON
        -DCMAKE_DISABLE_FIND_PACKAGE_Python3=ON

        -DCMAKE_REQUIRE_FIND_PACKAGE_ZLIB=ON
        -DCMAKE_REQUIRE_FIND_PACKAGE_Eigen3=ON

        -DCMAKE_DISABLE_FIND_PACKAGE_Graphviz=${TTK_DISABLE_FIND_GRAPHVIZ}
        -DCMAKE_REQUIRE_FIND_PACKAGE_Graphviz=${TTK_REQUIRE_FIND_GRAPHVIZ}

        -DTTK_BUILD_VTK_WRAPPERS=ON

        -DTTK_BUILD_DOCUMENTATION=OFF
        -DTTK_BUILD_PARAVIEW_PLUGINS=OFF
        -DTTK_BUILD_STANDALONE_APPS=OFF
        -DTTK_BUILD_VTK_PYTHON_MODULE=OFF

        -DTTK_ENABLE_EIGEN=ON
        -DTTK_ENABLE_ZLIB=ON
        -DTTK_ENABLE_GRAPHVIZ=${TTK_USE_GRAPHVIZ}
        -DTTK_ENABLE_OPENMP=${TTK_USE_OPENMP}
        -DTTK_ENABLE_SCIKIT_LEARN=OFF
        -DTTK_ENABLE_QHULL=OFF
        # needed to workaround a bug in TTKBaseConfig.cmake.in
        -DQhull_FOUND=OFF
        -DCGAL_FOUND=OFF

        # this depends in VTK::PythonInterpeter which is not there.
        -DVTK_MODULE_ENABLE_ttkCinemaDarkroom=NO

        # OpenMP mac workadound
        -DCMAKE_PREFIX_PATH=/opt/homebrew/opt/libomp
)
vcpkg_install_cmake()
vcpkg_copy_pdbs()
vcpkg_fixup_cmake_targets(
    CONFIG_PATH lib/cmake
    TARGET_PATH share
)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")

file(
    INSTALL ${SOURCE_PATH}/LICENSE 
    DESTINATION ${CURRENT_PACKAGES_DIR}/share/topology-tool-kit 
    RENAME copyright
)
